name: Deploy to FTP
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy site
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftps
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/sceptrade.com/
          state-name: .ftp-deploy-sync-state-site.json

      - name: Deploy liturgy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftps
          server: ${{ secrets.FTP_SERVER_LITURGY }}
          username: ${{ secrets.FTP_USERNAME_LITURGY }}
          password: ${{ secrets.FTP_PASSWORD_LITURGY }}
          local-dir: ./
          server-dir: /public_html/mitakachurch.com/liturgy/
          state-name: .ftp-deploy-sync-state-liturgy.json
